name: Auto Commit

on:
  schedule:
    - cron: "0 23 * * *"  # Runs every day at 11:00 PM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes
        run: |
          # Append current date and additional content to log.txt
          echo "Auto commit at $(date)" >> log.txt
          echo "Additional content here..." >> log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          # Only commit if there are changes staged
          git diff --cached --quiet || git commit -m "Automated commit on $(date)"
          git push
